- name: Afton Alps
  facebookUrl: https://www.facebook.com/aftonalpsmn
  mtbProjectUrl: https://www.mtbproject.com/directory/8008879/afton-state-park

- name: Battle Creek
  facebookUrl: https://www.facebook.com/battlecreekmountainbike
  mtbProjectUrl: https://www.mtbproject.com/directory/8013784/battle-creek-regional-park

- name: Monticello
  facebookUrl: https://www.facebook.com/BertramSingletrack
  mtbProjectUrl: https://www.mtbproject.com/trail/3505586/bertram-chain-of-lakes

- name: Carver Lake
  facebookUrl: https://www.facebook.com/mtbcarverlake/
  mtbProjectUrl: https://www.mtbproject.com/trail/3520161/carver-lake-park

- name: Cottage Grove Bike Park
  facebookUrl: https://www.facebook.com/cottagegrovebp/
  mtbProjectUrl: https://www.mtbproject.com/trail/7000927/west-draw-bike-park

- name: Elm Creek
  facebookUrl: https://www.facebook.com/ElmCreekSingletrack
  mtbProjectUrl: https://www.mtbproject.com/directory/8015292/elm-creek-park-reserve

- name: Hillside Park
  facebookUrl:
  mtbProjectUrl:

- name: Lake Rebecca
  facebookUrl: https://www.facebook.com/LakeRebeccaSingletrack/
  mtbProjectUrl: https://www.mtbproject.com/directory/8014842/lake-rebecca-park-reserve

- name: Lebanon Hills
  facebookUrl: https://www.facebook.com/lebanonhills/
  mtbProjectUrl: https://www.mtbproject.com/directory/8011629/lebanon-hills-regional-park

- name: MN River Bottoms
  facebookUrl:
  mtbProjectUrl: https://www.mtbproject.com/trail/7016269/minnesota-river-bottoms

- name: Murphy Hanrehan
  facebookUrl: https://www.facebook.com/MurphyHanrehanSingletrack/
  mtbProjectUrl: https://www.mtbproject.com/directory/8011510/murphy-hanrehan-park-reserve

- name: Salem Hills
  facebookUrl: https://www.facebook.com/Salem-Hills-Single-Track-1580089522261838/
  mtbProjectUrl: https://www.mtbproject.com/directory/8016604/salem-hills-park

- name: Terrace Oaks
  facebookUrl: https://www.facebook.com/Terrace-Oaks-Singletrack-Trail-1385424115111259
  mtbProjectUrl: https://www.mtbproject.com/trail/4350735/terrace-oaks-trail

- name: Theodore Wirth
  facebookUrl: https://www.facebook.com/theowirthsingletrack
  mtbProjectUrl: https://www.mtbproject.com/directory/8014425/theodore-wirth-park

- name: 7-Mile
  facebookUrl:
  mtbProjectUrl:

- name: Holzinger Lodge
  facebookUrl:
  mtbProjectUrl:

- name: Mt. Kato
  facebookUrl: https://www.facebook.com/joinMAMB/
  mtbProjectUrl: https://www.mtbproject.com/trail/7004427/kiwanis-mountain-bike-trail-mankato

- name: Memorial Trail
  facebookUrl:
  mtbProjectUrl:

- name: Grand Rapids
  facebookUrl:
  mtbProjectUrl:

- name: Jail Trail
  facebookUrl:
  mtbProjectUrl:

- name: Milaca
  facebookUrl:
  mtbProjectUrl:

- name: Hartley Park
  facebookUrl:
  mtbProjectUrl:

- name: Piedmont Trail
  facebookUrl:
  mtbProjectUrl:

- name: Whitetail Ridge
  facebookUrl:
  mtbProjectUrl:

- name: Woolly Trail
  facebookUrl:
  mtbProjectUrl:

- name: Levis Trow
  facebookUrl:
  mtbProjectUrl:
