#!/bin/bash

set -x

export JAVA_HOME=/etc/alternatives/java_sdk_1.8.0
export GRADLE_USER_HOME=$OPENSHIFT_DATA_DIR/gradle

LOG_FILE="${OPENSHIFT_LOG_DIR}/gradle.log"

cd "$OPENSHIFT_REPO_DIR"
./gradlew installShadowApp &> $LOG_FILE
